options:
  formatter: stylish
rules:
  # Extends
  extends-before-mixins: 1
  extends-before-declarations: 1
  placeholder-in-extend: 1

  # Mixins
  mixins-before-declarations: 0

  # Line Spacing
  one-declaration-per-line: 2
  empty-line-between-blocks: 2
  single-line-per-selector: 1

  # Disallows
  no-attribute-selectors: 0
  no-color-hex: 0
  no-color-keywords: 0
  no-color-literals: 0
  no-combinators: 0
  no-css-comments: 2
  no-debug: 1
  no-disallowed-properties: 0
  no-duplicate-properties: 2
  no-empty-rulesets: 2
  no-extends: 0
  no-ids: 1
  no-important: 1
  no-invalid-hex: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 2
  no-qualifying-elements: 1
  no-trailing-whitespace: 0
  no-trailing-zero: 1
  no-transition-all: 0
  no-universal-selectors: 0
  no-url-domains: 1
  no-url-protocols: 1
  no-vendor-prefixes: 0
  no-warn: 1
  property-units: 0

  # Nesting
  declarations-before-nesting: 2
  force-attribute-nesting: 1
  force-element-nesting: 0
  force-pseudo-nesting: 0

  # Name Formats
  class-name-format:
    - 2
    -
        allow-leading-underscore: true
        convention: ^[_a-z\-]+[\w\-]*$
  function-name-format: 1
  id-name-format: 0
  mixin-name-format: 1
  placeholder-name-format: 1
  variable-name-format:
    - 2
    -
        allow-leading-underscore: false
        convention: hyphenatedlowercase

  # Style Guide
  attribute-quotes: 1
  bem-depth: 0
  border-zero: 0
  brace-style: 2
  clean-import-paths: 1
  empty-args: 1
  hex-length: 0
  hex-notation: 0
  indentation:
    - 2
    -
        size: 4
  leading-zero: 0
  max-line-length: 0
  max-file-line-count: 0
  nesting-depth:
    - 2
    -
        max-depth: 3
  property-sort-order: 0
  pseudo-element: 1
  quotes: 1
  shorthand-values: 1
  url-quotes: 2
  variable-for-property: 0
  zero-unit: 1

  # Inner Spacing
  space-after-comma: 2
  space-before-colon: 2
  space-after-colon: 2
  space-before-brace: 2
  space-before-bang: 2
  space-after-bang: 2
  space-between-parens: 1
  space-around-operator: 0

  # Final Items
  trailing-semicolon: 2
  final-newline: 1
